server:
  port: 2030
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true 

spring:
  config:
    use-legacy-processing: true
  profiles:
    active:
    - local
  messages:
    basename: i18n/exception
    encoding: UTF-8  
  mvc:
    hiddenmethod:
      filter:
        enabled: true    
  jpa:
    open-in-view: true  
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false  
    properties:
      hibernate.format_sql: true  
   
        
# security:        
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 277412036240-rh9us6fhiueu6s9i0rr8cd3h6o578e6i.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#            - email
#            - profile       
        
        
        
        
        
        
        
        
        