server:
  port: 2030
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true 

spring:
  config:
    use-legacy-processing: true
  profiles:
    active:
    - local
  messages:
    basename: i18n/exception
    encoding: UTF-8
#  web:
#    resources:
#      static-locations:
#      - classpath:/static-test/    
  mvc:
#    static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true    
  jpa:
    open-in-view: true  
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false  
    properties:
      hibernate.format_sql: true  
  
        
        
        
        
        
        
        
        
        